### ISSUE TITLE
Fixing Unavailable Portions in Download Links

### ISSUE THREAD

**Issue by guanrongLi** [LaMP-Benchmark/LaMP#4]
I noticed that some of the provided time-based data download links of LaMP 4: Personalized News Headline Generation task are currently unavailable. I would like to request a fix for these unavailable links.
<img width="919" alt="Screenshot 2023-06-07 at 4 39 10 PM" src="https://github.com/LaMP-Benchmark/LaMP/assets/43704639/ab84f8a4-ffc8-447d-96d3-817168a414a6">

**Comment by alirezasalemi7** [comment]
Hi, Thank you so much for notifying me about this. I think it should be fixed now. LMK if there is any other problem with the links.

**Comment by guanrongLi** [comment]
Thanks very much for your support. The links are fine now.
